repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: trailing-whitespace

      - id: mixed-line-ending
        args: [ --fix=lf ]

  - repo: local
    hooks:
      - id: luacheck
        name: luacheck
        language: system
        entry: luacheck
        types: [lua]
        args: [-q]
